{:ground-children {:ground-part {:position [0.0 0.0 0.0],
                                 :rotation [-1.0 0.0 0.0 90]}}
 :parts {:ground-part {:type :ground,
                       :color [40 40 40],
                       :value 0,
                       :scale [12 12 1],
                       :children {:block29650 {:position [0.75 -0.25 0.25],
                                               :rotation [1.0 0.0 0.0 90]}}},
         :block29650 {:type :block,
                      :color :white,
                      :value 0,
                      :scale [0.5 0.5 0.5],
                      :children {:track29651 {:position [0.0 1.25 0.0],
                                              :rotation [0.0 1.0 0.0 0.0]}}},
         :track29651 {:type :track,
                      :color :red,
                      :value 0,
                      :scale [0.1 1 0.1],
                      :children nil}}}
